ci: report "npm WARN deprecated" #4229
Problem:
Deprecated dependencies may not be noticed for a long time.

    npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
    npm WARN deprecated winston@3.7.1: Please use version 3.6.0 or >3.7.1 when available due to https://github.com/winstonjs/winston/issues/2103

Solution:
Collect these warnings when running CI.
TODO: fail if new warnings are found.

diff --git a/buildspec/linuxTests.yml b/buildspec/linuxTests.yml
--- a/buildspec/linuxTests.yml
+++ b/buildspec/linuxTests.yml
@@ -33,25 +33,11 @@ phases:
                 fi
             - |
                 {
-                    set -e
-                    set -o pipefail
-                    _PROMISE_REJ_MSG='rejected promise not handled'
-                    mkfifo testout
-                    (cat testout &)
-                    xvfb-run npm test --silent | tee testout \
-                        | grep -v 'undefined..reading..range' \
-                        | grep -v CODEWHISPERER_INLINE_UPDATE_LOCK_KEY \
-                        | { >testout-rej grep --line-buffered "$_PROMISE_REJ_MSG" || true; }
-                    if [ -s testout-rej ] ; then
-                        echo ''
-                        cat testout-rej | sort
-                        printf '\n\nERROR: Found %s "%s" in test output (see above).\n%s\n\n' \
-                            "$(cat testout-rej | wc -l | tr -d ' ')" \
-                            "$_PROMISE_REJ_MSG" \
-                            '       This typically indicates a bug. Read https://developer.mozilla.org/docs/Web/JavaScript/Guide/Using_promises#error_handling'
-                        # TODO: fail the CI job
-                        # exit 1;
-                    fi
+                    . buildspec/shared/common.sh
+                    2>&1 xvfb-run npm test --silent | run_and_report \
+                        'rejected promise not handled' \
+                        'This typically indicates a bug. Read https://developer.mozilla.org/docs/Web/JavaScript/Guide/Using_promises#error_handling' \
+                        || true # TODO: fail the CI job
                 }
             - VCS_COMMIT_ID="${CODEBUILD_RESOLVED_SOURCE_VERSION}"
             - CI_BUILD_URL=$(echo $CODEBUILD_BUILD_URL | sed 's/#/%23/g') # Encode `#` in the URL because otherwise the url is clipped in the Codecov.io site
