delete beta_version variable

diff --git a/buildspec/release/70checkmarketplace.yml b/buildspec/release/70checkmarketplace.yml
--- a/buildspec/release/70checkmarketplace.yml
+++ b/buildspec/release/70checkmarketplace.yml
@@ -22,37 +22,33 @@ phases:
     build:
         commands:
             - VERSION=$(node -e "console.log(require('./packages/${TARGET_EXTENSION}/package.json').version);")
-            # get extension name, also an old version for beta testing
+            # get extension name, if in beta, use some hard-coded recent version
             - |
                 if [ "${TARGET_EXTENSION}" = "amazonq" ]; then
                   extension_name="amazonwebservices.amazon-q-vscode"
-                  beta_version="@1.43.0"
+                  [ "$STAGE" != "prod" ] && VERSION="1.43.0" || true
                 elif [ "${TARGET_EXTENSION}" = "toolkit" ]; then
                   extension_name="amazonwebservices.aws-toolkit-vscode"
-                  beta_version="@3.42.0"
+                  [ "$STAGE" != "prod" ] && VERSION="3.42.0" || true
                 else
                   echo checkmarketplace: "Unknown TARGET_EXTENSION: ${TARGET_EXTENSION}"
                   exit 1
                 fi
-            # If in beta, install specific extension versions
             - |
                 if [ "$STAGE" != "prod" ]; then
-                  VERSION=${beta_version#@}
-                  echo "checkmarketplace: Non-production stage detected. Installing beta version '${VERSION}'."
-                else
-                  beta_version=""
+                  echo "checkmarketplace: Non-production stage detected. Installing hardcoded version '${VERSION}'."
                 fi
-            # keep reinstalling the extension until the desired version is updated. Otherwise fail on codebuild timeout (1 hour).
+            # keep installing the desired extension version until successful. Otherwise fail on codebuild timeout (1 hour).
             - |
                 while true; do
                   code --uninstall-extension "${extension_name}" --no-sandbox --user-data-dir /tmp/vscode
-                  code --install-extension "${extension_name}${beta_version}" --no-sandbox --user-data-dir /tmp/vscode
+                  code --install-extension "${extension_name}@${VERSION}" --no-sandbox --user-data-dir /tmp/vscode
                   cur_version=$(code --list-extensions --show-versions --no-sandbox --user-data-dir /tmp/vscode | grep ${extension_name} | cut -d'@' -f2)
                   if [ "${cur_version}" = "${VERSION}" ]; then
                     echo "checkmarketplace: Extension ${extension_name} is updated to version '${cur_version}.'"
                     break
                   else
-                    echo "checkmarketplace: Current version '${cur_version}' does not match expected version '${VERSION}'. Retrying..."
+                    echo "checkmarketplace: Expected extension version '${VERSION}' has not been successfully installed. Retrying..."
                   fi
                   sleep 120 # Wait for 2 minutes before retrying
                 done
